# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: maths

on:
    push:
        branches: [master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: maths test
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: test
      run: |
        python setup.py test
